### PR TITLE
Update scales.json

### PR DESCRIPTION
**Pull request by hippich**
Found a comprehensive list of scales here - http://web.archive.org/web/20141220065316/http://www.eigenlabs.com/wiki/2.0/Scale_Arrays/ and just adapted it for the usage with  ZynSeq.

### CODE REVIEW

**Comment by jofemodo** [comment]
Uoauuu! This looks really cool, @hippich ! I'm sure Mr. @riban-bw  would agree ;-)
BTW, i really would like to have a "GM percussion" scale. It's a must.

Thanks!

**Comment by jofemodo** [comment]
Could we reshape the ordering? It seems quite arbitrary ...

**Comment by hippich** [comment]
I have no opinion on the order... What are your preferences?

**Comment by hippich** [comment]
> Uoauuu! This looks really cool, @hippich ! I'm sure Mr. @riban-bw would agree ;-) BTW, i really would like to have a "GM percussion" scale. It's a must.
> 
> Thanks!

I am total noob in music theory.... what is "GM percussion" scale? Googling failed me on this one :)

**Comment by hippich** [comment]
Hm...There are quite a few repeating scales under different names... I guess these should not be repeated, right? (again, i have no idea about music theory, maybe it is incorrect?)

**Comment by riban-bw** [comment]
@jofemodo GM percussion _should_already be there. I will have to check if it's not. I certainly designers it. I will take a look at this later.

**Comment by riban-bw** [comment]
Please remove duplicate scales, chosing the best name for the remaining scale.
Order of scales is tricky. We could go alphabetical but that probably isn't most useful. We could list the most common western scales first as that might suit a high percentage of users but we should make other scales accessible, i.e. not hide middle eastern and oriental scales where users won't find them.

**Comment by hippich** [comment]
I've removed duplicates. As for re-ordering - I am really having no clue here... =) blues i think is "western" - so I could move it closer to the top?

**Comment by jofemodo** [comment]
Regarding order, "Bebop" are jazz scales (aka occidental too). Also, i have no idea of what is Pa, Pb & Pd. Could we find beter names for those? Anyway, i think we would better discuss this subject on the forum. There are zynthianics with great knowledge about this subject.

Thanks!

**Comment by jofemodo** [comment]
I just remembered this:

https://github.com/zynthian/zynthian-issue-tracking/issues/425

The current "automatic detection" of drum instruments is pretty deficient, specially for soundfonts, whitch are the most used drum instruments. We should add the "GM percussion" map to the scale list, so it could be selected by hand. Selecting "GM percussion" as default map for channel 10 could interesting too.

Regards,

**Comment by jofemodo** [comment]
@riban-bw , should we merge this and think about re-ordering, etc. in a second round?

**Comment by riban-bw** [comment]
I will take a look this evening (a bit busy today) and validate it works as expected.

**Comment by riban-bw** [comment]
No, we have to do something with the order of these scales. There are some that I feel should definitely be at the top of the list but are way down, e.g. Natural Minor, Blues and pentatonic scales. Also, related scales should probably be consecutive, e.g. the various Locrian scales. 

I have made some edits to the patch which I hope will be pulled in. This can now be merged.

**Pull request merged**
